#!/bin/bash
mkdir $HOME/.config $HOME/.local/bin -p

dir=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd)

find dot-* -depth -maxdepth 0 | while IFS= read -r line; do
    name=$(echo "$line" | sed 's/^dot-/./')
    cd $line 2> /dev/null
    if [ $? -eq 0 ]; then
        stow . -t $HOME/$name
        cd ..
    else
        ln -s $dir/$line $HOME/$name
    fi
done
