"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = '$directory-$username$character'
right_format = '$nix_shell'

[character]
format = '\$ '

[directory]
format = '[\[$path\]]($style)'

[username]
format = '[\[$user\]]($style)'
disabled = false
show_always = true

[nix_shell]
disabled = false
